### ISSUE TITLE
Can it run on macOs?

### ISSUE THREAD

**Issue by sppet** [mborho/rem#11]
Hello, 

Thanks for this tool, I like to use it in my Linux environments but my main machine is a mac. Is there any way to install this to a mac?

Thanks

**Comment by mborho** [comment]
Hi, thanks for your report!

Currently building for MacOS won't work, but I'll investigate if it can be fixed!

**Comment by mborho** [comment]
You should now be able to install on macOS with `go get github.com/mborho/rem` or by downloading the binary from the [release page](https://github.com/mborho/rem/releases/tag/v0.15.0).

**Comment by sppet** [comment]
Wow, thank you very much.
